# shared_constants.py

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 6667

# Comandos estándar del protocolo IRC (RFC 2812)
IRC_COMMANDS = {
    "PASS": "Establece contraseña de conexión",
    "USER": "Registra al usuario con detalles adicionales",
    "NICK": "Establece apodo o cambia el actual",
    "OPER": "Otorga privilegios de operador",
    "QUIT": "Desconectarse del servidor",
    "SQUIT": "Desconectar links de servidores(solo operadores)",
    "SERVICE": "Registra un nuevo servicio",
    "JOIN": "Unirse a un canal",
    "PART": "Salir de un canal",
    "MODE": "Cambia el modo de un usuario o canal",
    "TOPIC": "Establece o consulta el tema del canal",
    "NAMES": "Lista los usuarios de un canal",
    "LIST": "Lista canales disponibles",
    "INVITE": "Invitar a un usuario a un canal",
    "KICK": "Expulsar a un usuario de un canal",
    "MOTD": "Recibe el 'Mensaje del Día' del servidor pedido",
    "LUSERS": "Solicita estadísticas sobre el tamaño de la red IRC",
    "VERSION": "Solicitar la versión del servidor",
    "STATS": "Solicitar estadísticas del servidor",
    "LINKS": "Lista servidores conectados",
    "TIME": "Consulta la hora del servidor",
    "CONNECT": "Conectar a otro servidor",
    "SERVLIST": "Lista servicios conectados actualmente y visibles para el cliente",
    "SQUERY": "Envía mensaje a un servicio",
    "TRACE": "Traza la ruta de conexión",
    "ADMIN": "Información del administrador del servidor",
    "INFO": "Información del servidor",
    "PRIVMSG": "Enviar un mensaje privado",
    "NOTICE": "Enviar una notificación sin respuesta",
    "WHO": "Consulta información sobre usuarios",
    "WHOIS": "Consulta información detallada de un usuario",
    "WHOWAS": "Consulta información sobre un usuario desconectado",
    "PING": "Verificar la latencia con el servidor",
    "PONG": "Responder a un PING",
    "AWAY": "Establecer mensaje de ausencia",
    "REHASH": "Recargar configuración del servidor",
    "DIE": "Cerrar el servidor (operadores)",
    "RESTART": "Reiniciar el servidor",
    "ERROR":"Mandar mensaje de error(normalmente en conexiones server-server)",
    "KILL": "Cerrar la conexión de un cliente(operadores)",
    "SUMMON":"Solicita a un servidor IRC que intente notificar a un usuario conectado al sistema local",
    "USERS":"Solicita la lista de usuarios conectados al servidor",
    "WALLOPS":"Envía un mensaje global a todos los operadores de la red.",
    "USERHOST":"Solicita información sobre uno o más apodos en la red.",
    "ISON":"Verifica si uno o más apodos están conectados"
}
