# shared_constants.py

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 6667

# Comandos estándar del protocolo IRC (RFC 2812)
IRC_COMMANDS = {
    "PASS": "Establece contraseña de conexión",
    "USER": "Registra al usuario con detalles adicionales",
    "NICK": "Establece apodo o cambia el actual",
    "OPER": "Otorga privilegios de operador",
    "QUIT": "Desconectarse del servidor",
    "SQUIT": "Desconectar links de servidores(solo operadores)",
    "SERVICE": "Registra un nuevo servicio",
    "JOIN": "Unirse a un canal",
    "PART": "Salir de un canal",
    "MODE": "Cambia el modo de un usuario o canal",
    "TOPIC": "Establece o consulta el tema del canal",
    "NAMES": "Lista los usuarios de un canal",
    "LIST": "Lista canales disponibles",
    "INVITE": "Invitar a un usuario a un canal",
    "KICK": "Expulsar a un usuario de un canal",
    "MOTD": "Recibe el 'Mensaje del Día' del servidor pedido",
    "LUSERS": "Solicita estadísticas sobre el tamaño de la red IRC",
    "VERSION": "Solicitar la versión del servidor",
    "STATS": "Solicitar estadísticas del servidor",
    "LINKS": "Lista servidores conectados",
    "TIME": "Consulta la hora del servidor",
    "CONNECT": "Conectar a otro servidor",
    "SERVLIST": "Lista servicios conectados actualmente y visibles para el cliente",
    "SQUERY": "Envía mensaje a un servicio",
    "TRACE": "Traza la ruta de conexión",
    "ADMIN": "Información del administrador del servidor",
    "INFO": "Información del servidor",
    "PRIVMSG": "Enviar un mensaje privado",
    "NOTICE": "Enviar una notificación sin respuesta",
    "WHO": "Consulta información sobre usuarios",
    "WHOIS": "Consulta información detallada de un usuario",
    "WHOWAS": "Consulta información sobre un usuario desconectado",
    "PING": "Verificar la latencia con el servidor",
    "PONG": "Responder a un PING",
    "AWAY": "Establecer mensaje de ausencia",
    "REHASH": "Recargar configuración del servidor",
    "DIE": "Cerrar el servidor (operadores)",
    "RESTART": "Reiniciar el servidor",
    "ERROR":"Mandar mensaje de error(normalmente en conexiones server-server)",
    "KILL": "Cerrar la conexión de un cliente(operadores)",
    "SUMMON":"Solicita a un servidor IRC que intente notificar a un usuario conectado al sistema local",
    "USERS":"Solicita la lista de usuarios conectados al servidor",
    "WALLOPS":"Envía un mensaje global a todos los operadores de la red.",
    "USERHOST":"Solicita información sobre uno o más apodos en la red.",
    "ISON":"Verifica si uno o más apodos están conectados"
}

response_patterns = {
    "/nick": r" NICK ",
    "/join": r" JOIN ",
    "/part": r" PART ",
    "/privmsg": r" PRIVMSG ",
    "/notice": r" NOTICE ",
    "/quit": "ERROR :Closing link",
    "/mode": r" MODE ",
    "/topic": (r" TOPIC ", r" 331 ", r" 332 "),
    "/names": (r' 353 ', r' 366 '),
    "/list": (r' 322 ', r' 323 '),
    "/invite": r" INVITE ",
    "/kick": r" KICK ",
    "/who": (r' 352 ', r' 315 '),
    "/whois": (r' 311 ', r' 318 '),  
    "/whowas": (r' 314 ', r' 369 '), 
    "/oper": r" 381 ",
    "/kill": r" KILL ",
    "/wallops": r" WALLOPS ",
    "/version": r" 351 ",
    "/stats": (r' 249 ', r' 219 '),
    "/links": (r' 364 ', r' 365 '),
    "/time": r" 391 ",
    "/admin": (r' 256 ', r' 259 '),
    "/info": (r' 371 ', r' 374 '),
    "/trace": (r' 200 ', r' 262 '),
    "/connect": r" CONNECT ",
    "/squit": r" SQUIT ",
    "/ping": r" PONG ",
    "/pong": r" PING ",
    "/away": r" 306 ",
    "/rehash": r" REHASH ",
    "/die": r" DIE ",
    "/restart": r" RESTART ",
    "/userhost": r" 302 ",
    "/ison": r" 303 ",
    "/service": r" 383 ",
    "/motd": (r' 375 ', r' 376 '),
    "/lusers": (r' 251 ', r' 266 '),
    "/servlist": (r' 234 ', r' 235 '),
    "/squery": r" SQUERY ",
    "/summon": r" 342 ",
    "/users": (r' 392 ', r' 395 '),
    "ERROR": {
        "401": "No existe canal/nickname",
        "402": "No existe el servidor",
        "403": "No existe el canal",
        "404": "No puedes enviar al canal",
        "405": "Te has unido a demasiados canales",
        "406": "No existió el nickname",
        "407": "Demasiados objetivos",
        "408": "No existe el servicio",
        "421": "Comando desconocido",
        "422": "No se pudo abrir archivo MOTD/No hay MOTD",
        "423": "No hay información administrativa",
        "431": "Falta nickname",
        "432": "Nickname inválido",
        "433": "Nickname ya está en uso",
        "437": "Nickname/canal no disponible temporalmente",
        "441": "El usuario objetivo no está en el canal",
        "442": "No estás en el canal",
        "443": "El usuario ya pertenece al canal",
        "444": "Usuario no logeado",
        "445": "Servidor no soporta SUMMON",
        "446": "Servidor no soporta USERS",
        "461": "Faltan parámetros",
        "462": "Ya registrado",
        "464": "Contraseña incorrecta",
        "465": "Exiliado del servidor",
        "471": "No puedes unirte al canal(canal lleno)",
        "473": "No puedes unirte al canal(solo con invitación)",
        "474": "No puedes unirte al canal(exiliado del canal)",
        "475": "No puedes unirte al canal(+k)",
        "476": "Nombre de canal inválido",
        "477": "El canal no soporta modos",
        "482": "No tienes permiso para realizar esta acción",
        "481": "Necesitas privilegios de operador",
        "483": "No puedes matar un servidor",
        "484": "Conexión restringida",
        "485": "No eres el operador original del canal",
        "491": "Credenciales incorrectas",
        "501": "Modo no reconocido",
        "502": "No puedes cambiar el modo de otro usuario(fuera de un canal)"
    }
}
